set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)

if(CMAKE_HOST_SYSTEM_NAME STREQUAL Linux)
    set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
    set(CMAKE_C_COMPILER arm-none-eabi-gcc)
    set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL FreeBSD)
    set(GCC_ARM_EMBEDDED_BIN_DIR "/usr/local/gcc-arm-embedded/bin")
    set(CMAKE_ASM_COMPILER ${GCC_ARM_EMBEDDED_BIN_DIR}/arm-none-eabi-gcc)
    set(CMAKE_C_COMPILER ${GCC_ARM_EMBEDDED_BIN_DIR}/arm-none-eabi-gcc)
    set(CMAKE_CXX_COMPILER ${GCC_ARM_EMBEDDED_BIN_DIR}/arm-none-eabi-g++)
else()
    message(FATAL_ERROR "Unsupported OS")
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
